table FactGraduation
	lineageTag: 970ac184-d3a2-4805-adfe-6c0aecd01ed6

	column Outcome
		dataType: string
		lineageTag: 47dd8287-c717-49e8-9154-78efac64391b
		summarizeBy: none
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	column CohortTerm
		dataType: string
		lineageTag: 3bd718f5-4d41-4b9c-a604-a9ad891569ad
		summarizeBy: none
		sourceColumn: CohortTerm

		annotation SummarizationSetBy = Automatic

	column CohortYear
		dataType: int64
		formatString: 0
		lineageTag: 5a4c5e01-2491-44e2-bf41-6d040ee00c8a
		summarizeBy: none
		sourceColumn: CohortYear

		annotation SummarizationSetBy = Automatic

	column GraduationRate
		dataType: double
		lineageTag: 49bd6f7b-9042-40be-a219-40066ae04294
		summarizeBy: sum
		sourceColumn: GraduationRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactGraduation = m
		mode: import
		queryGroup: '03 Model'
		source =
				let
				    Source = Raw_GraduationRates_ST,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"TABLE 1.32", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34"}),
				    #"Removed Top Rows" = Table.Skip(#"Removed Other Columns",4),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Column1", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Fall 1991", type any}, {"Fall 1992", type any}, {"Fall 1993", type any}, {"Fall 1994", type any}, {"Fall 1995", type any}, {"Fall 1996", type any}, {"Fall 1997", type any}, {"Fall 1998", type any}, {"Fall 1999", type any}, {"Fall 2000", type any}, {"Fall 2001", type any}, {"Fall 2002", type any}, {"Fall 2003", type any}, {"Fall 2004", type any}, {"Fall 2005", type any}, {"Fall 2006", type any}, {"Fall 2007", type any}, {"Fall 2008", type any}, {"Fall 2009", type any}, {"Fall 2010", type any}, {"Fall 2011", type any}, {"Fall 2012", type any}, {"Fall 2013", type any}, {"Fall 2014", type any}, {"Fall 2015", type any}, {"Fall 2016", type any}, {"Fall 2017", type any}, {"Fall 2018", type any}, {"Fall 2019", type any}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Column2", "Section"}, {"Column3", "Population"}, {"Column4", "Metric"}, {"Column5", "Submetric"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Column1"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filled Down" = Table.FillDown(#"Removed Blank Rows",{"Section", "Population", "Metric"}),
				    #"Filtered Rows" = Table.SelectRows(#"Filled Down", each ([Section] = "6-YEAR GRADUATION RATE") and ([Population] = "All Students") and ([Metric] = "Graduated")),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Outcome", each if [Submetric] = "within 4 years" then "4-Year Graduation Rate" else if [Submetric] = null then "6-Year Graduation Rate" else if [Submetric] = "in the 5th year" then "5th-Year Increment" else if [Submetric] = "in the 6th year" then "6th-Year Increment" else null),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Conditional Column", each ([Outcome] = "4-Year Graduation Rate" or [Outcome] = "6-Year Graduation Rate")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"Section", "Population", "Metric", "Submetric"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"Outcome", "Fall 1991", "Fall 1992", "Fall 1993", "Fall 1994", "Fall 1995", "Fall 1996", "Fall 1997", "Fall 1998", "Fall 1999", "Fall 2000", "Fall 2001", "Fall 2002", "Fall 2003", "Fall 2004", "Fall 2005", "Fall 2006", "Fall 2007", "Fall 2008", "Fall 2009", "Fall 2010", "Fall 2011", "Fall 2012", "Fall 2013", "Fall 2014", "Fall 2015", "Fall 2016", "Fall 2017", "Fall 2018", "Fall 2019"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Reordered Columns", {"Outcome"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "CohortTerm"}, {"Value", "GraduationRate"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns1", "CohortTerm", "CohortTerm - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column",{{"CohortTerm - Copy", "CohortYear"}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Renamed Columns2", {{"CohortYear", each Text.AfterDelimiter(_, "Fall "), type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Extracted Text After Delimiter",{{"CohortYear", Int64.Type}, {"GraduationRate", type number}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type2",{"Outcome", "CohortTerm", "CohortYear", "GraduationRate"})
				in
				    #"Reordered Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

